### ISSUE TITLE
Missing Network IDs

### ISSUE THREAD

**Issue by 95CivicSi** [jasonwynn10/VanillaEntityAI#15]
A large number of entities do not have their network ID set in the class file.
Examples can be found in all of the passiveagressive mobs.  Many others exist as well, I haven't looked through all entities yet.

https://github.com/jasonwynn10/VanillaEntityAI/blob/master/src/jasonwynn10/VanillaEntityAI/entity/passiveaggressive/Wolf.php

**Comment by jasonwynn10** [comment]
The entities without ids are not registered to spawn, so there shouldn't be any problems. They just need implemented

**Comment by 95CivicSi** [comment]
It showed up with the summon command, although the PR I submitted will keep it from being a problem.
