### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Karanztez** [jasonwynn10/VanillaEntityAI#18]
- Can you fix the problem mob spawner?

- Can you make it happen in the general world like Purexentite?

**Comment by jasonwynn10** [comment]
Please clarify

**Comment by Karanztez** [comment]
https://youtu.be/FqxA8_nh-Qw

In world and mob spawner

**Comment by DenielWorld** [comment]
Isnt it dependent on the day/night like in vanilla?

**Comment by jasonwynn10** [comment]
No, not at all. https://minecraft.gamepedia.com/Spawn#Bedrock_Edition
