### ISSUE TITLE
(Not an Issue for most) Could you change/add this?

### ISSUE THREAD

**Issue by MistakingManx** [jasonwynn10/VanillaEntityAI#20]
Could you make it so we can disable mob spawning in specific worlds while allowing mobs to spawn in others?
I don't want creepers and zombies spawning on the hub..

**Comment by jasonwynn10** [comment]
set your hub to peaceful difficulty

**Comment by jasonwynn10** [comment]
Completed by e434e4bd70f6d0821823a0776af4663e2c4c6728
