### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by junxiesky** [jasonwynn10/VanillaEntityAI#31]
PHP Fatal error:  Trait method initEntity has not been applied, because there are collisions with other trait methods on jasonwynn10\VanillaEntityAI\entity\hostile\Drowned in phar:///home/2/plugins/VanillaEntityAI_dev-84.phar/src/jasonwynn10/VanillaEntityAI/entity/hostile/Drowned.php on line 9
Fatal error: Trait method initEntity has not been applied, because there are collisions with other trait methods on jasonwynn10\VanillaEntityAI\entity\hostile\Drowned in phar:///home/2/plugins/VanillaEntityAI_dev-84.phar/src/jasonwynn10/VanillaEntityAI/entity/hostile/Drowned.php on line 9

**Comment by dapwestwood** [comment]
Same here

**Comment by jasonwynn10** [comment]
I can't help if I don't know what release you are using.

**Comment by dapwestwood** [comment]
I use the latest dev build

**Comment by mote166** [comment]
same issue here using pmmp 3.9.1

**Comment by junxiesky** [comment]
I did use 3.9.3

**Comment by ZZWILLIAMXXTrue** [comment]
Same here using 3.9.3

**Comment by A354-PH** [comment]
Same
