### ISSUE TITLE
Server Crashing oof here the error

### ISSUE THREAD

**Issue by note3crafter** [jasonwynn10/VanillaEntityAI#35]
Error: Argument 1 passed to jasonwynn10\VanillaEntityAI\entity\neutral\Item::push() must be an instance of jasonwynn10\VanillaEntityAI\entity\CreatureBase, instance of jasonwynn10\VanillaEntityAI\entity\passive\Villager given, called in phar:///home/CBS/plugins/VanillaEntityAI_dev-88.phar/src/jasonwynn10/VanillaEntityAI/entity/CollisionCheckingTrait.php on line 25
File: plugins/VanillaEntityAI_dev-88.phar/src/jasonwynn10/VanillaEntityAI/entity/neutral/Item
Line: 39
Type: TypeError

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: VanillaEntityAI v1.0.0-alpha4

Code:

Backtrace:
```
#0 plugins/VanillaEntityAI_dev-88.phar/src/jasonwynn10/VanillaEntityAI/entity/CollisionCheckingTrait(25): jasonwynn10\VanillaEntityAI\entity\neutral\Item->push(object jasonwynn10\VanillaEntityAI\entity\passive\Villager)
#1 plugins/VanillaEntityAI_dev-88.phar/src/jasonwynn10/VanillaEntityAI/entity/CollisionCheckingTrait(12): jasonwynn10\VanillaEntityAI\entity\passive\Villager->checkNearEntities()
#2 src/pocketmine/entity/Entity(1481): jasonwynn10\VanillaEntityAI\entity\passive\Villager->entityBaseTick(integer 1)
#3 plugins/VanillaEntityAI_dev-88.phar/src/jasonwynn10/VanillaEntityAI/entity/CollisionCheckingTrait(34): pocketmine\entity\Entity->onUpdate(integer 209096)
#4 src/pocketmine/level/Level(853): jasonwynn10\VanillaEntityAI\entity\passive\Villager->onUpdate(integer 209096)
#5 src/pocketmine/level/Level(786): pocketmine\level\Level->actuallyDoTick(integer 209096)
#6 src/pocketmine/Server(2445): pocketmine\level\Level->doTick(integer 209096)
#7 src/pocketmine/Server(2576): pocketmine\Server->checkTickUpdates(integer 209096, double 1567536013.3903)
#8 src/pocketmine/Server(2345): pocketmine\Server->tick()
#9 src/pocketmine/Server(2205): pocketmine\Server->tickProcessor()
#10 src/pocketmine/Server(1784): pocketmine\Server->start()
#11 src/pocketmine/PocketMine(275): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[10] /home/CBS/, string[18] /home/CBS/plugins/)
#12 src/pocketmine/PocketMine(299): pocketmine\server()
#13 (1): require(string[65] phar:///home/CBS/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
```
PocketMine-MP version: 3.9.4 [Protocol 361]
Git commit: 1be6783c34ec51b578464899994285a7e8188590
uname -a: Linux Noteland-Netzwerk 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64
PHP Version: 7.2.19
Zend version: 3.2.0
OS : Linux, linux

**Comment by DenielWorld** [comment]
steps to reproduce?

**Comment by DenielWorld** [comment]
I believe that is because it is trying to push() the villager entity, but the push() method is not implemented in Villager
