### ISSUE TITLE
this plugin is usable or is in beta / alpha?

### ISSUE THREAD

**Issue by RubyTemple** [jasonwynn10/VanillaEntityAI#37]
this plugin is usable or is in beta / alpha?

**Comment by Wertzui123** [comment]
You can use it, but many features are not implemented due minecrafts entity system is very complex.

**Comment by RubyTemple** [comment]
> You can use it, but many features are not implemented due minecrafts entity system is very complex.

What mob ai is implemented?

**Comment by Wertzui123** [comment]
I don't think so

**Comment by jasonwynn10** [comment]
Zombies, Skeletons, and Creepers all have partial AI. If they are attacked it turns on.
Natural spawning can be enabled in the server.properties file.
