### ISSUE TITLE
Server crash using pmmp 3.11.2

### ISSUE THREAD

**Issue by alackmann** [jasonwynn10/VanillaEntityAI#39]
Return value of jasonwynn10\VanillaEntityAI\entity\hostile\Zombie::setMainHandItem() must be an instance of jasonwynn10\VanillaEntityAI\entity\ItemHolderTrait, instance of jasonwynn10\VanillaEntityAI\entity\hostile\Drowned returned

https://crash.pmmp.io/view/3470959

Havent seen an alpha release lately. Are you still working on this @jasonwynn10 ?

**Comment by rjworks** [comment]
he not working on it anymore you can use other plugin
