### ISSUE TITLE
What's difference and why use that plugin?

### ISSUE THREAD

**Issue by NycuRO** [jasonwynn10/VanillaEntityAI#6]
What's difference of PureEntitiesX and that plugin? Why use that and not PureEntities?

Btw, do movement ticking and loading entities in other thread if you don't want laggy plugin. ;)

**Comment by jasonwynn10** [comment]
The difference between this and PureEntitiesX is basically everything. This plugin is not designed to be customizable and only does vanilla Mob AI.

As for custom threading, it's overcomplicating things. The plugin currently runs relatively lagless and is not even noticeable on the client.

VanillaEntityAI Timings: https://timings.pmmp.io/?id=448
PureEntitiesX Timings: https://timings.pmmp.io/?id=451
Just found this out too but it appears that PureEntitiesX is cheating in the timings. Notice how it says there are only 3 entities. I tested with 50 zombies for each plugin

**Comment by NycuRO** [comment]
Still is laggy. Try use multi thread.

**Comment by jasonwynn10** [comment]
Offloading the work onto a seperate thread won't make anything faster. In fact, it would probably make the  plugin operate slower due to the overhead of serialization over threads.

**Comment by NycuRO** [comment]
lol.
