### ISSUE TITLE
AutoSpawn/Despawn Tasks extends Thread?

### ISSUE THREAD

**Issue by NycuRO** [jasonwynn10/VanillaEntityAI#9]
Why not?

i mean about that: https://github.com/pmmp/pthreads

**Comment by NycuRO** [comment]
@Sandertv Yes dude but it's impossible to make this non laggy? Not exists any methods?

**Comment by NycuRO** [comment]
What's your purpose to make plugins non laggy when in gonna using ticking main and motion?

**Comment by Sandertv** [comment]
¯\_(ツ)_/¯

**Comment by NycuRO** [comment]
For exemple, you said is not better to use threading / async. So then why pmmp uses? 

Exemple: events: https://github.com/pmmp/PocketMine-MP/issues/2470

**Comment by jasonwynn10** [comment]
@NycuRO sander is saying that threading, while effective in handling EXTREMELY LARGE loads will create more lag for the server for small loads. Entity ticking is considered a relatively small load, so threading would increase the overall server lag

**Comment by jasonwynn10** [comment]
Also, please read what you are posting about. it directly says in that PR that threading does not equal async

**Comment by NycuRO** [comment]
anyway, i can't think it's not any possiblity to make this faster. I like a developer when he give all to make them project clear and best performance possible and that i hope from here, because i know exist competent people for that.

**Comment by jasonwynn10** [comment]
@NycuRO If you think you can do this better, by all means do it yourself.
